---
- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
    state: present
    force_apt_get: yes
    update_cache: yes

- name: add Docker apt key
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: add Docker apt repository
  apt_repository:
    repo: "deb [arch={{ docker_apt_sources_arch }}] {{ docker_apt_sources_uri }} {{ docker_apt_sources_suite }} stable"
    state: present
    filename: docker

- name: install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    force_apt_get: yes
    update_cache: yes

- name: start and enable daemon
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: set non-root users
  user:
    name: "{{ user }}"
    state: present
    groups:
      - docker
    append: yes
  loop: "{{ docker_users }}"
  loop_control:
    loop_var: user
