---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/bionic64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../resources/tests/journald-logging
  lint:
    name: flake8
