---
- name: prepare
  hosts: instance
  gather_facts: false
  tasks:
    - name: install Python 3 for Ansible
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get -y install python3-minimal)
      become: true
      changed_when: false
