---
- name: converge
  hosts: instance
  tasks:
    - name: create user for remapping
      user:
        name: testuser
        state: present
        password: "!"
        system: yes
        create_home: no

    - name: create group for remapping
      group:
        name: testgroup
        state: present
        system: yes

    - name: configure /etc/subuid
      lineinfile:
        line: testuser:1100000:65536
        path: /etc/subuid
        state: present

    - name: configure /etc/subgid
      lineinfile:
        line: testgroup:2200000:65536
        path: /etc/subgid
        state: present

    - name: install Docker
      import_role:
        name: docker
