---
name: CI
on:
  - push
jobs:
  test:
    name: run role tests
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          path: docker
      - name: set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get --yes install virtualbox
          wget https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
          sudo apt-get --yes  install ./vagrant_2.2.6_x86_64.deb
          sudo apt-get install --fix-broken
          python -m pip install --requirement "$GITHUB_WORKSPACE/docker/requirements.txt"
      - name: run templates rendering tests
        run: python -m unittest discover --verbose --start-directory "$GITHUB_WORKSPACE/docker"
      - name: "debug: show Vagrant version"
        run: vagrant --version
