---
name: CI
on:
  - push
jobs:
  test:
    name: run role tests
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          path: docker
      - name: set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: install dependencies
        run: |
          python -m pip install --requirement "$GITHUB_WORKSPACE/docker/requirements.txt"
