---
name: CI
on:
  - push
jobs:
  test:
    name: run role tests
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          path: docker
      - name: Show workspace directory content
        run: ls -l $GITHUB_WORKSPACE
